# CAED LAB MID
## AGHA AMMAR KHAN 210300
## BCE-F-21-A

In [1]:
import numpy as np
import pandas as pd

file1=input("Enter the File name of BEEP 2A to access class data file: ")
file2=input("Enter the File name of MTS 2A to access class data file: ")
file3=input("Enter the File name of MTS 2B to access class data file: ")
file4=input("Enter the File name of BEBME 1A to access class data file: ")
BEEP=pd.read_csv(file1)
MTS2A=pd.read_csv(file2)
MTS2B=pd.read_csv(file3)
BEBME1A=pd.read_csv(file4)

BEEP =pd.DataFrame(BEEP) 
MTS2A=pd.DataFrame(MTS2A)
MTS2B=pd.DataFrame(MTS2B)
BEBME1A=pd.DataFrame(BEBME1A)

Enter the File name of BEEP 2A to access class data file: BEEP 2A.csv
Enter the File name of MTS 2A to access class data file: MTS 2A.csv
Enter the File name of MTS 2B to access class data file: MTS 2B.csv
Enter the File name of BEBME 1A to access class data file: BEBME 1A.csv

In [2]:
BEEP

,Roll numbers,Names,Lab Performances (out of 15),Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Midterm (out of 55),Final term (out of 50),CEA (out of 20)
0,210319,Muhammad Ammar Bajwa,7,7,15,15,7,7,15,15,...,12,8,3,14,15,4,1,42.5,39,7
1,210323,Waleed Hussain,7,7,10,10,15,15,15,13,...,10,12,2,6,8,9,14,34.0,19,15
2,210325,Shahzaib Malik,7,7,15,15,15,15,11,11,...,4,7,5,10,4,7,12,30.5,38,20
3,210327,Muhammad Tayyab Saddiq,7,7,7,7,15,15,9,9,...,8,12,4,4,4,9,0,22.5,31,14
4,210331,Hadia Zainab Raza,7,7,11,4,15,15,3,5,...,0,7,10,13,8,10,14,29.5,13,16
5,210335,Syeda Imtashal Fatima Jaffari,7,7,12,12,8,8,11,10,...,6,9,12,4,5,12,9,28.0,25,2
6,210339,Azlan Muhammad,7,7,7,0,12,12,1,7,...,6,11,4,3,10,7,2,23.0,44,14
7,210341,Abdullah Zahid,7,7,10,10,15,15,15,15,...,14,12,10,14,4,7,14,34.5,24,3
8,210351,Muammar Rehman,7,7,8,8,9,9,7,7,...,6,11,1,4,14,9,14,26.5,31,4
9,210355,Abdullah Khan,7,7,7,7,15,15,9,9,...,5,14,4,0,0,4,4,14.5,14,18
10,210357,Usama Khalid,7,7,8,8,12,7,12,12,...,15,7,14,4,15,9,9,24.0,22,7
11,210359,Muhammad Kazim,7,7,12,12,12,12,15,15,...,15,8,11,11,4,14,9,33.0,44,7
12,210363,Muhammad Talha,7,7,10,10,15,15,7,3,...,0,13,1,4,3,9,14,8.0,47,19
13,210365,Muhammad Usman,7,7,15,15,15,15,15,15,...,8,0,14,6,15,2,8,28.0,1,13
14,210369,Mudassar Zahoor,7,7,15,15,15,15,13,13,...,7,2,13,10,14,0,11,39.5,34,0
15,210371,Abdul Baasit,7,7,15,15,15,15,15,15,...,6,1,8,14,13,0,4,30.0,18,15
16,210373,Taha Khalid,7,7,9,11,12,12,11,11,...,13,6,9,14,3,5,1,31.0,34,4
17,210377,Abdullah Zulfiqar,7,7,7,7,15,15,14,15,...,7,0,6,6,13,6,11,28.5,32,1
18,210379,Usama Zulfiqar,7,7,10,10,15,15,7,8,...,7,15,15,8,4,11,6,28.5,24,3
19,210381,Ahmad Mahtab Cheema,7,7,15,15,15,15,6,8,...,13,2,9,10,13,12,11,34.5,40,4
20,210383,Adnan Bashir,7,7,10,10,7,7,8,8,...,6,15,5,15,2,11,15,19.0,6,18
21,211986,Shaoib ul Hassan,7,7,12,12,15,15,14,14,...,14,3,15,0,11,4,6,31.0,24,16
22,211988,Muhammad Ali Khan,7,7,12,12,15,15,7,5,...,6,14,15,9,8,0,2,13.0,49,19

In [3]:
MTS2A

,Roll numbers,Names,Lab Performances (out of 15),Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Midterm (out of 55),Final term (out of 50),CEA (out of 20)
0,201113,Shaheer Faisal,7,7,8,8,7,7,10,10,...,12,5,8,12,1,6,12,32.5,8,20
1,201128,Mati Ur Rehman Ahmed,15,15,7,7,7,7,9,9,...,12,6,6,11,8,2,10,19.0,26,17
2,210559,Taimoor Qamar,15,15,13,13,7,7,8,8,...,5,8,14,15,12,13,1,31.5,16,6
3,211176,Muhammad Junaid,7,13,12,12,7,7,7,11,...,8,13,1,5,2,6,12,39.0,37,12
4,211184,Hafiz Haider Farooq,11,15,15,15,7,4,8,4,...,1,13,13,13,15,7,6,41.0,22,12
5,211187,Muhammad Taha Khalid,15,15,8,8,7,7,8,8,...,10,10,7,7,12,8,13,37.5,18,1
6,211190,Areeba Nazim,7,7,15,15,7,7,8,8,...,12,4,13,4,8,9,5,36.5,31,0
7,211191,Muhammad Mubeen Anjum,15,15,8,8,7,7,9,9,...,7,14,13,10,10,5,8,36.0,22,0
8,211194,Sania Ali,14,14,13,13,7,7,10,9,...,9,15,10,0,7,5,15,27.0,45,2
9,211196,Norose Chohan,7,7,8,8,7,4,0,7,...,5,12,4,3,5,11,3,34.5,9,3
10,211197,Shazil Sajjad,15,15,10,10,7,7,15,15,...,5,6,4,1,4,8,15,50.5,42,19
11,211199,Abdullah Bin Masood,15,15,12,12,7,7,12,12,...,7,15,5,2,15,9,8,28.5,50,7
12,211200,Madeeha Fayyaz,15,15,7,7,7,7,7,7,...,7,11,8,4,7,2,8,27.0,25,11
13,211202,Shereen Zainab,14,14,7,7,7,7,13,13,...,5,12,13,7,9,5,15,26.5,24,4
14,211209,Arooj Aftab,13,13,7,7,7,7,4,8,...,0,5,1,10,3,1,1,13.0,39,14
15,211212,Abdullah Ilyas,15,15,7,7,7,7,8,8,...,0,1,15,12,5,13,3,30.5,49,5
16,211214,Samiullah,11,11,10,10,7,7,9,9,...,4,9,3,2,13,15,14,29.0,2,11
17,211215,Waris Shah,7,2,8,8,15,15,13,13,...,12,13,5,3,3,5,14,33.5,41,1
18,211217,Rafay Ali Hassnain,13,13,8,7,15,15,8,8,...,11,5,1,12,9,10,3,14.5,24,5
19,211221,Areeba Nisar,12,12,8,8,7,7,8,8,...,3,5,10,12,11,11,7,14.0,14,3
20,211223,Hassan Ali Janjua,4,2,7,7,7,7,11,11,...,6,9,7,11,3,3,2,16.0,15,14
21,211224,Muhammad Shehroz Khan,3,3,7,7,7,7,12,7,...,11,12,3,14,5,8,3,30.0,15,20
22,211230,Hasnain Khan Afridi,8,8,7,7,15,15,13,13,...,4,15,8,10,7,12,6,14.5,22,18
23,211232,Muhammad Waqar,15,15,15,15,7,7,8,8,...,2,15,0,13,15,2,1,35.5,23,11
24,211233,Muhammad Abdullah,15,15,12,12,7,7,8,8,...,0,6,9,10,11,3,6,30.5,28,15
25,211236,Muhammad Muzammil,15,15,8,8,7,7,8,8,...,9,9,3,1,14,13,1,28.0,7,17
26,211239,Danyal Ahmed,6,12,8,8,7,7,7,7,...,7,2,1,0,4,13,9,33.0,1,3
27,211242,Ali Torab,15,15,7,7,7,7,9,9,...,7,11,0,4,8,2,0,36.5,17,17
28,211254,Rabiah,14,14,7,7,7,7,10,10,...,3,13,5,10,8,7,12,29.5,49,3
29,211257,Etizaz Zahid,9,9,7,7,7,7,15,15,...,10,9,10,8,9,12,8,26.0,28,4
30,211260,Salahuddin Muhammad Abdullah,14,14,8,8,7,7,10,10,...,3,14,6,2,12,10,13,36.0,7,12
31,211263,Muhammad Mubeen Rubbani,10,14,12,12,7,7,12,12,...,10,3,10,4,0,6,0,38.5,42,19
32,211266,Alishba Syed,8,8,7,0,7,7,10,10,...,3,8,11,15,14,6,10,11.5,40,3
33,211269,Salman Ali,8,15,7,7,7,7,8,8,...,4,0,4,13,14,15,4,28.0,17,10
34,211275,Saif Ur Rehman,15,15,7,7,7,7,3,9,...,13,3,3,11,7,12,6,11.5,20,10
35,211278,Ali Hassan,12,12,8,8,7,7,9,9,...,8,7,14,5,12,6,0,31.5,14,7
36,211281,Muhammad Ahsan Mujahid,15,15,7,7,7,7,7,7,...,14,7,3,9,11,11,9,20.0,1,17
37,211284,Izza Nadeem,15,15,7,7,7,7,7,7,...,3,0,15,9,3,15,4,29.0,16,19
38,211287,Hassan Hafeez,8,8,7,7,15,15,9,9,...,11,13,9,10,4,15,10,22.5,5,7
39,212002,Muhammad Sohaib,11,15,12,12,7,7,7,7,...,10,8,0,0,7,15,14,29.5,3,14
40,212003,Faizan Ahmed Siddiqui,15,15,12,12,7,7,9,9,...,0,12,4,7,8,15,15,38.5,32,20
41,212004,Azhar Ali,8,8,8,8,7,7,11,11,...,8,10,5,7,12,4,5,32.0,47,8

In [4]:
MTS2B

,Roll numbers,Names,Lab Performances (out of 15),Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Midterm (out of 55),Final term (out of 50),CEA (out of 20)
0,201186,Ahmad Mohid Ullah,4,4,13,13,7,13,12,8,...,15,8,0,7,15,7,3,30.5,45,13
1,211165,Muhammad Ali Hashmi,7,7,10,10,7,2,12,9,...,2,8,6,7,0,13,11,41.5,49,3
2,211180,Muhammad Bilal,7,7,15,15,15,15,13,13,...,11,3,11,1,13,8,3,51.5,18,13
3,211183,Sahil Khan,7,3,7,0,9,9,7,7,...,7,3,5,1,14,4,10,24.0,44,16
4,211192,Malik Muhammad Ibrahim,15,15,8,8,15,15,15,11,...,1,0,10,4,14,8,5,24.5,17,20
5,211195,Muhammad Talal Arshad,7,7,7,7,15,14,15,11,...,13,10,1,6,6,1,5,25.5,18,9
6,211198,Muhammad Hasnain Raza,15,15,9,9,15,15,13,9,...,4,11,11,13,8,0,6,28.5,46,10
7,211201,Muhammad Moin Dildar,15,11,8,8,8,8,10,10,...,14,3,1,0,12,11,13,26.0,49,16
8,211204,Anas Iqbal,7,7,15,11,15,15,7,7,...,1,10,12,6,6,6,3,29.0,47,18
9,211207,Amna Zafar,7,7,7,7,15,15,13,13,...,13,8,14,1,1,5,2,37.0,10,7
10,211219,Akbar Aziz Qureshi,7,7,8,8,13,13,7,7,...,11,1,6,3,4,6,15,26.5,24,9
11,211222,Muhammad Ali Rafay,7,7,7,7,12,12,7,7,...,14,4,3,12,13,11,1,20.0,37,3
12,211225,Iqra Noor,7,7,7,4,3,7,10,10,...,12,2,5,3,2,1,3,18.5,18,14
13,211228,Ahmad Ibrahim Khan,7,7,10,10,9,9,9,9,...,8,12,2,13,14,2,5,34.5,12,9
14,211231,Afaq Ul Hassan,7,7,9,9,13,15,9,9,...,13,12,5,8,6,2,9,21.5,19,13
15,211234,Malik Maaz Muhammad Khan,7,7,7,7,12,12,12,11,...,9,9,13,6,0,0,2,33.0,43,7
16,211235,Muhammad Talha,7,7,8,8,15,15,7,7,...,5,6,7,4,5,6,1,28.5,28,6
17,211237,Muhammad Abdullah Gill,0,7,7,7,11,11,7,7,...,7,7,4,11,9,1,6,34.0,9,1
18,211238,Shanza Kanwal,7,7,9,9,11,11,7,7,...,14,12,14,9,9,5,1,18.5,14,17
19,211240,Ahmad Hassan,7,7,10,10,15,15,8,8,...,3,13,11,14,12,14,2,33.5,13,15
20,211241,Danish Abdullah,4,7,7,7,11,11,8,8,...,3,14,2,9,7,7,14,30.0,34,0
21,211244,Muhammad Ryan Sabaja,15,15,10,10,15,15,8,8,...,11,13,6,7,4,7,2,24.5,4,1
22,211246,Tayyab Nouman,7,7,15,15,15,15,12,12,...,11,4,13,4,14,8,14,30.0,48,16
23,211247,Abdul Rehman,0,7,8,3,7,2,12,12,...,2,7,7,3,2,4,13,21.5,9,2
24,211249,Nusaiba Howraa,7,7,9,9,13,13,8,8,...,11,12,5,13,11,12,13,37.0,34,14
25,211256,Muhammad Ahsan Sajjad,15,11,8,3,7,7,9,7,...,7,6,1,10,13,13,14,15.0,44,14
26,211262,Haider Sajjad,7,2,9,9,11,11,11,11,...,9,1,5,3,14,10,10,18.5,37,8
27,211265,Muhammad Mahmood Ghauri,0,7,15,15,15,15,13,12,...,1,12,4,5,4,9,7,31.0,4,13
28,211267,Muhammad Suleman,15,15,8,8,8,8,7,7,...,3,11,15,9,15,4,11,18.5,32,17
29,211268,Wadha Saddal,7,7,9,6,15,15,13,13,...,14,11,13,6,0,11,11,41.0,34,12
30,211277,Muhammad Saud Dar,7,7,15,11,15,15,13,12,...,6,1,6,3,10,0,13,27.5,2,18
31,211280,Muhammad Usman,7,7,14,14,15,15,13,13,...,12,10,14,8,2,11,1,46.5,34,17
32,211282,Ahmed Javed,7,7,8,3,7,7,7,7,...,13,2,7,5,2,6,9,26.0,48,7
33,211288,Hafiz Muhammad Shoaib Islam,15,15,12,12,15,15,11,11,...,9,3,10,11,0,1,2,42.0,41,3
34,211291,Muhammad Salman,4,4,4,7,7,7,7,7,...,7,10,1,9,6,2,11,14.0,40,10

In [5]:
BEBME1A

,Roll numbers,Names,Lab Performances (out of 15),Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Midterm (out of 55),Final term (out of 50),CEA (out of 20)
0,211135,Muniba Ali,12,12,15,15,13,13,15,12,...,15,15,11,8,8,8,15,32.0,18,19
1,211136,Ifrah Kamran,14,14,13,13,13,13,3,8,...,15,2,15,15,11,9,6,21.0,47,8
2,211142,Iman Ali Shahid,11,11,6,12,11,11,7,2,...,15,8,2,15,3,9,9,13.0,5,10
3,211143,Kahab Abdullah,14,14,13,7,15,15,12,11,...,13,9,3,11,7,11,1,35.0,0,20
4,211145,Noor-Ul-Ain,15,15,15,15,14,14,12,4,...,15,14,15,0,9,1,6,31.0,11,16
5,211148,Syeda Iqra Naveen,11,11,14,14,12,12,9,11,...,15,7,14,2,10,0,0,30.0,41,18
6,211149,Aamnah Sultan,14,14,12,12,11,11,8,0,...,15,0,14,7,10,8,5,18.0,5,7
7,211150,Muhammad Ahmed,14,14,14,14,11,11,5,9,...,12,4,5,5,1,1,6,18.0,28,9
8,211152,Muhammad Arslan Siddique,10,12,15,15,13,13,12,0,...,12,6,5,1,8,6,14,30.0,29,1
9,211153,Muqaddas Shakeel,10,12,12,12,11,11,14,7,...,14,4,7,10,13,1,9,11.5,11,14
10,211154,Anum Faisal,11,11,13,13,12,12,5,7,...,15,0,4,6,3,0,4,28.0,44,2
11,211155,Khunsha Ahmed,14,14,12,12,11,11,12,10,...,15,1,8,1,8,6,13,12.0,29,1
12,211156,Rania Khalid,7,0,7,7,0,2,11,8,...,15,4,7,10,15,10,0,8.5,10,6
13,211157,Zunaira Shafqat,10,10,5,12,7,7,12,6,...,1,3,0,7,14,7,15,4.5,28,0
14,211158,Zohaib Hassan Shakir,12,8,6,13,14,14,11,12,...,0,3,15,14,0,4,7,23.0,36,11
15,211159,Aroosha Irfan,15,15,13,13,8,10,1,2,...,14,4,8,14,6,13,9,32.0,35,16
16,211160,Laiba Idrees Kayani,12,12,14,14,12,12,5,13,...,14,6,1,4,0,14,14,8.0,42,0
17,211161,Shanzay Nadeem,13,13,13,13,4,11,0,0,...,15,3,7,6,0,2,5,12.0,49,11
18,211162,Manahil Fatima,15,11,13,13,10,10,5,6,...,15,15,15,7,5,3,10,13.0,4,20
19,211164,Manal Haider,13,13,11,11,10,9,8,13,...,14,10,11,0,6,7,8,10.0,48,1
20,211166,Ahsan Naveed,15,15,13,13,12,12,15,14,...,14,15,10,7,10,8,5,14.5,17,15
21,211167,Rida-E-Fatima,15,15,14,14,12,12,3,4,...,15,10,6,13,12,3,3,19.0,9,2
22,211168,Nimra Riaz,5,12,13,13,12,12,2,12,...,15,15,8,9,9,13,4,16.0,21,18
23,211170,Mahnoor Jabeen,12,12,12,12,10,10,9,2,...,15,1,11,6,2,2,2,27.0,37,10
24,211173,Aliza Ranash,14,14,15,15,12,12,5,3,...,15,6,8,7,6,4,15,32.0,16,2
25,211174,Muhammad Talha Imad El Din,12,12,13,13,9,9,15,6,...,13,2,1,9,10,1,5,12.0,5,7
26,211175,Muhammad Hammad Javaid,12,12,14,14,11,11,3,14,...,12,3,7,2,15,2,11,11.0,42,17
27,211940,Sadeem Ali,14,14,13,13,13,13,12,3,...,15,2,9,13,9,1,10,21.0,25,14
28,212045,Muhammad Abdur Rehman Ali,15,15,14,14,13,13,15,5,...,15,1,8,0,5,1,9,21.0,36,0
29,212094,Abdul Rehman,12,12,13,13,14,14,15,12,...,15,13,7,4,11,14,5,29.0,39,9

In [26]:
def grades(dataframe):
    grades=np.array([])
    grandTotalColumn=np.array(dataframe)
    for i in grandTotalColumn:
        if i >= 85:
            grades=np.append(grades,"A")
        elif i>=75:
             grades=np.append(grades,"B+")
        elif i>=70:
             grades=np.append(grades,"B")
        elif i>=65:
             grades=np.append(grades,"C+")
        elif i>=60:
             grades=np.append(grades,"C")
        elif i>=50:
             grades=np.append(grades,"D")
        elif i<50:
             grades=np.append(grades,"F")
            
    grandTotalColumn=pd.DataFrame(grandTotalColumn)
    grades=pd.DataFrame(grades)
    grading=pd.concat([grades],axis=1)
    grading=np.array(grading)
    grading=pd.DataFrame(grading)
    return grading

In [27]:
def Result(dictionary,pandaDataFrame):
    df=pd.Series(dictionary)
    array=np.array(pandaDataFrame)
    LR=array[:,2:16]
    LP=array[:,16:30]
    MT=array[:,30]
    FT=array[:,31]
    CEA=array[:,32]
    rollNumber=array[:,0]
    Name=array[:,1]
    LP=np.sum(LP,axis=1)
    LR=np.sum(LR,axis=1)
    LRTotal=np.multiply((df['LR']),(LR/210))
    LPTotal=np.multiply((df['LP']),(LP/210))
    MTTotal=np.multiply((df['MT']),(MT/55))
    FTTotal=np.multiply((df['FT']),(FT/50))
    CEATotal=np.multiply((df["CEA"]),(CEA/20))
    rollNumber=pd.DataFrame(rollNumber)
    Name=pd.DataFrame(Name)
    lr=pd.DataFrame(LRTotal)
    lp=pd.DataFrame(LPTotal)
    mt=pd.DataFrame(MTTotal)
    ft=pd.DataFrame(FTTotal)
    cea=pd.DataFrame(CEATotal)
    result=pd.concat([lp,lr,mt,ft,cea],axis=1)
    GrandTotal=np.sum(result,axis=1)
    GrandTotal=np.array(GrandTotal)
    GrandTotal=pd.DataFrame(GrandTotal)
    Grade=grades(GrandTotal)
    result=pd.concat([rollNumber,Name,lp,lr,mt,ft,cea,GrandTotal,Grade],axis=1)
    result=np.array(result)
    result=pd.DataFrame(result)
    result=np.array(result)
    newFile=pd.DataFrame(result,columns=["Roll numbers","Names","Lab Performance Total","Lab Report Total","Mid Term Total","Final Term Total","CEA Total","Grand Total","Grades"])
    return newFile

In [28]:
def creatFile(fileName,dataframe):
    File=dataframe.to_csv(fileName)

In [29]:
def searchByRollNumber(dataframe,rollnumber):
    name=dataframe[(dataframe["Roll numbers"]==rollnumber)]
    print(name)

In [33]:
while True:
    print("Press 1 for CE-112L MTS II B \nPress 2 for CE-112L MTS II-A \nPress 3 for CE-112L BEEP II-A \nPress 4 for CE-115L BEBME 1A.")
    choice=int(input("Enter: "))
    if choice==1:
        LabReport=int(input("Enter the Lab report weightage: "))
        LabPerformance=int(input("Enter the Lab Performance weightage: "))
        MidTerm=int(input("Enter the Mid Term weightage: "))
        FinalTerm=int(input("Enter the Final Term weightage: "))
        CEA=int(input("Enter the CEA weightage: "))
        Total=LabReport+LabPerformance+MidTerm+FinalTerm+CEA
        weightages={"LR":LabReport,"LP":LabPerformance,"MT":MidTerm,"FT":FinalTerm,"CEA":CEA}
        if Total>100 or Total<100:
            print("Re Enter the weightages. Can't be greater than or less than 100")
            continue
        else:
            while True:
                print("Enter 1 to display class Result \n Enter 2 to generate class result in .csv file \n Enter 3 to search the reslut of a student")
                op1=int(input("Enter: "))
                if op1==1:
                    print(Result(weightages,MTS2B))
                elif op1==2:
                    creatFile("MTS 2B RESULT.csv",Result(weightages,MTS2B))
                elif op1==3:
                    name=int(input("Enter the roll number of the student to search the result"))
                    searchByRollNumber(Result(weightages,MTS2B),name)
                print("Enter 0 to Enter in other class and 5 to continue")    
                op1=int(input("Enter: "))
                if op1==0:
                    break
                else:
                    continue
                        
    elif choice==2:
        LabReport=int(input("Enter the Lab report weightage: "))
        LabPerformance=int(input("Enter the Lab Performance weightage: "))
        MidTerm=int(input("Enter the Mid Term weightage: "))
        FinalTerm=int(input("Enter the Final Term weightage: "))
        CEA=int(input("Enter the CEA weightage: "))
        Total=LabReport+LabPerformance+MidTerm+FinalTerm+CEA
        weightages={"LR":LabReport,"LP":LabPerformance,"MT":MidTerm,"FT":FinalTerm,"CEA":CEA}
        if Total>100 or Total<100:
            print("Re Enter the weightages. Can't be greater than or less than 100")
            continue
        else:
            while True:
                print("Enter 1 to display class Result \n Enter 2 to generate class result in .csv file \n Enter 3 to search the reslut of a student")
                op1=int(input("Enter: "))
                if op1==1:
                    print(Result(weightages,MTS2A))
                elif op1==2:
                    creatFile("MTS 2A RESULT.csv",Result(weightages,MTS2A))
                elif op1==3:
                    name=int(input("Enter the roll number of the student to search the result"))
                    searchByRollNumber(Result(weightages,MTS2A),name)
                print("Enter 0 to Enter in other class and 5 to continue")    
                op1=int(input("Enter: "))
                if op1==0:
                    break
                else:
                    continue
            
    elif choice==3:
        LabReport=int(input("Enter the Lab report weightage: "))
        LabPerformance=int(input("Enter the Lab Performance weightage: "))
        MidTerm=int(input("Enter the Mid Term weightage: "))
        FinalTerm=int(input("Enter the Final Term weightage: "))
        CEA=int(input("Enter the CEA weightage: "))
        Total=LabReport+LabPerformance+MidTerm+FinalTerm+CEA
        weightages={"LR":LabReport,"LP":LabPerformance,"MT":MidTerm,"FT":FinalTerm,"CEA":CEA}
        if Total>100 or Total<100:
            print("Re Enter the weightages. Can't be greater than or less than 100")
            continue
        else:
            while True:
                print("Enter 1 to display class Result \n Enter 2 to generate class result in .csv file \n Enter 3 to search the reslut of a student")
                op1=int(input("Enter: "))
                if op1==1:
                    print(Result(weightages,BEEP))
                elif op1==2:
                    creatFile("BEEP 2A RESULT.csv",Result(weightages,BEEP))
                elif op1==3:
                    name=int(input("Enter the roll number of the student to search the result"))
                    searchByRollNumber(Result(weightages,BEEP),name)
                print("Enter 0 to Enter in other class and 5 to continue")    
                op1=int(input("Enter: "))
                if op1==0:
                    break
                else:
                    continue
              
    elif choice==4:
        LabReport=int(input("Enter the Lab report weightage: "))
        LabPerformance=int(input("Enter the Lab Performance weightage: "))
        MidTerm=int(input("Enter the Mid Term weightage: "))
        FinalTerm=int(input("Enter the Final Term weightage: "))
        CEA=int(input("Enter the CEA weightage: "))
        Total=LabReport+LabPerformance+MidTerm+FinalTerm+CEA
        weightages={"LR":LabReport,"LP":LabPerformance,"MT":MidTerm,"FT":FinalTerm,"CEA":CEA}
        if Total>100 or Total<100:
            print("Re Enter the weightages. Can't be greater than or less than 100")
            continue
        else:
            while True:
                print("Enter 1 to display class Result \n Enter 2 to generate class result in .csv file \n Enter 3 to search the reslut of a student")
                op1=int(input("Enter: "))
                if op1==1:
                    print(Result(weightages,BEBME1A))
                elif op1==2:
                    creatFile("BEBME 1A RESULT.csv",Result(weightages,BEBME1A))
                elif op1==3:
                    name=int(input("Enter the roll number of the student to search the result"))
                    searchByRollNumber(Result(weightages,BEBME1A),name)
                print("Enter 0 to Enter in other class and 5 to continue")    
                op1=int(input("Enter: "))
                if op1==0:
                    break
                else:
                    continue
                    
        print("Enter 0 to end and 5 to continue")
        choice=int(input("Enter: "))
        if choice==0:
            break
        elif choice==1:
            continue

Press 1 for CE-112L MTS II B
Press 2 for CE-112L MTS II-A
Press 3 for CE-112L BEEP II-A
Press 4 for CE-115L BEBME 1A.
Enter: 1
Enter the Lab report weightage: 20
Enter the Lab Performance weightage: 20
Enter the Mid Term weightage: 20
Enter the Final Term weightage: 20
Enter the CEA weightage: 20
Enter 1 to display class Result
 Enter 2 to generate class result in .csv file
 Enter 3 to search the reslut of a student
Enter: 1
   Roll numbers                        Names Lab Performance Total  \
0        201186            Ahmad Mohid Ullah             13.333333
1        211165          Muhammad Ali Hashmi             12.619048
2        211180               Muhammad Bilal             11.904762
3        211183                   Sahil Khan             10.190476
4        211192       Malik Muhammad Ibrahim             11.809524
5        211195        Muhammad Talal Arshad             12.095238
6        211198        Muhammad Hasnain Raza             12.571429
7        211201         Muhammad Moin Dildar             12.047619
8        211204                   Anas Iqbal              9.952381
9        211207                   Amna Zafar             12.571429
10       211219           Akbar Aziz Qureshi             10.761905
11       211222           Muhammad Ali Rafay             12.380952
12       211225                    Iqra Noor              9.428571
13       211228           Ahmad Ibrahim Khan              12.47619
14       211231               Afaq Ul Hassan             12.952381
15       211234     Malik Maaz Muhammad Khan             11.619048
16       211235               Muhammad Talha              9.714286
17       211237       Muhammad Abdullah Gill             11.238095
18       211238                Shanza Kanwal             13.619048
19       211240                 Ahmad Hassan             14.857143
20       211241              Danish Abdullah             10.190476
21       211244         Muhammad Ryan Sabaja             11.428571
22       211246                Tayyab Nouman             13.428571
23       211247                 Abdul Rehman              7.904762
24       211249               Nusaiba Howraa              13.52381
25       211256        Muhammad Ahsan Sajjad             10.190476
26       211262                Haider Sajjad                  12.0
27       211265      Muhammad Mahmood Ghauri             11.809524
28       211267             Muhammad Suleman             14.380952
29       211268                 Wadha Saddal             13.714286
30       211277            Muhammad Saud Dar             11.333333
31       211280               Muhammad Usman              13.52381
32       211282                  Ahmed Javed             11.619048
33       211288  Hafiz Muhammad Shoaib Islam             10.095238
34       211291              Muhammad Salman              8.857143

   Lab Report Total Mid Term Total Final Term Total CEA Total Grand Total  \
0           9.52381      11.090909             18.0      13.0   64.948052
1          9.714286      15.090909             19.6       3.0   60.024242
2         14.857143      18.727273              7.2      13.0   65.689177
3          8.666667       8.727273             17.6      16.0   61.184416
4         13.809524       8.909091              6.8      20.0   61.328139
5         14.095238       9.272727              7.2       9.0   51.663203
6         14.952381      10.363636             18.4      10.0   66.287446
7         11.619048       9.454545             19.6      16.0   68.721212
8          13.52381      10.545455             18.8      18.0   70.821645
9         12.380952      13.454545              4.0       7.0   49.406926
10        11.809524       9.636364              9.6       9.0   50.807792
11         9.142857       7.272727             14.8       3.0   46.596537
12        10.666667       6.727273              7.2      14.0   48.022511
13        12.190476      12.545455              4.8       9.0   51.012121
14        11.809524       7.818182              7.6      13.0   53.180087
15        11.904762           12.0             17.2       7.0    59.72381
16        10.571429      10.363636             11.2       6.0   47.849351
17         9.714286      12.363636              3.6       1.0   37.916017
18        10.190476       6.727273              5.6      17.0   53.136797
19        13.047619      12.181818              5.2      15.0    60.28658
20         8.761905      10.909091             13.6       0.0   43.461472
21        14.095238       8.909091              1.6       1.0     37.0329
22        16.095238      10.909091             19.2      16.0     75.6329
23         8.190476       7.818182              3.6       2.0    29.51342
24        10.857143      13.454545             13.6      14.0   65.435498
25         9.809524       5.454545             17.6      14.0   57.054545
26        13.238095       6.727273             14.8       8.0   54.765368
27        13.714286      11.272727              1.6      13.0   51.396537
28        11.904762       6.727273             12.8      17.0   62.812987
29        11.619048      14.909091             13.6      12.0   65.842424
30        13.047619           10.0              0.8      18.0   53.180952
31        14.857143      16.909091             13.6      17.0   75.890043
32         9.238095       9.454545             19.2       7.0   56.511688
33        16.095238      15.272727             16.4       3.0   60.863203
34        10.190476       5.090909             16.0      10.0   50.138528

   Grades
0       C
1       C
2      C+
3       C
4       C
5       D
6      C+
7      C+
8       B
9       F
10      D
11      F
12      F
13      D
14      D
15      D
16      F
17      F
18      D
19      C
20      F
21      F
22     B+
23      F
24     C+
25      D
26      D
27      D
28      C
29     C+
30      D
31     B+
32      D
33      C
34      D
Enter 0 to Enter in other class and 5 to continue
Enter: 2
Enter 1 to display class Result
 Enter 2 to generate class result in .csv file
 Enter 3 to search the reslut of a student
Enter: 3
Enter the roll number of the student to search the result211219
   Roll numbers               Names Lab Performance Total Lab Report Total  \
10       211219  Akbar Aziz Qureshi             10.761905        11.809524

   Mid Term Total Final Term Total CEA Total Grand Total Grades
10       9.636364              9.6       9.0   50.807792      D
Enter 0 to Enter in other class and 5 to continue
Enter: 0
Press 1 for CE-112L MTS II B
Press 2 for CE-112L MTS II-A
Press 3 for CE-112L BEEP II-A
Press 4 for CE-115L BEBME 1A.
Enter: 2
Enter the Lab report weightage: 20
Enter the Lab Performance weightage: 25
Enter the Mid Term weightage: 15
Enter the Final Term weightage: 20
Enter the CEA weightage: 20
Enter 1 to display class Result
 Enter 2 to generate class result in .csv file
 Enter 3 to search the reslut of a student
Enter: 1
   Roll numbers                         Names Lab Performance Total  \
0        201113                Shaheer Faisal             16.309524
1        201128          Mati Ur Rehman Ahmed                  17.5
2        210559                 Taimoor Qamar             18.571429
3        211176               Muhammad Junaid             12.738095
4        211184           Hafiz Haider Farooq             16.904762
5        211187          Muhammad Taha Khalid             18.333333
6        211190                  Areeba Nazim             15.714286
7        211191         Muhammad Mubeen Anjum             19.047619
8        211194                     Sania Ali             16.666667
9        211196                 Norose Chohan              15.47619
10       211197                 Shazil Sajjad             16.071429
11       211199           Abdullah Bin Masood             16.071429
12       211200                Madeeha Fayyaz             10.833333
13       211202                Shereen Zainab             17.142857
14       211209                   Arooj Aftab                  12.5
15       211212                Abdullah Ilyas             14.404762
16       211214                     Samiullah             15.595238
17       211215                    Waris Shah              15.47619
18       211217            Rafay Ali Hassnain             13.928571
19       211221                  Areeba Nisar             15.238095
20       211223             Hassan Ali Janjua             11.071429
21       211224         Muhammad Shehroz Khan             10.595238
22       211230           Hasnain Khan Afridi             16.309524
23       211232                Muhammad Waqar             16.190476
24       211233             Muhammad Abdullah                  15.0
25       211236             Muhammad Muzammil             14.642857
26       211239                  Danyal Ahmed             13.690476
27       211242                     Ali Torab             12.738095
28       211254                        Rabiah             15.119048
29       211257                  Etizaz Zahid             17.857143
30       211260  Salahuddin Muhammad Abdullah             15.595238
31       211263       Muhammad Mubeen Rubbani              14.52381
32       211266                  Alishba Syed              17.02381
33       211269                    Salman Ali                  15.0
34       211275                Saif Ur Rehman              14.52381
35       211278                    Ali Hassan             16.666667
36       211281        Muhammad Ahsan Mujahid             15.952381
37       211284                   Izza Nadeem             17.619048
38       211287                 Hassan Hafeez             15.595238
39       212002               Muhammad Sohaib             14.880952
40       212003         Faizan Ahmed Siddiqui             17.380952
41       212004                     Azhar Ali             16.071429

   Lab Report Total Mid Term Total Final Term Total CEA Total Grand Total  \
0          9.238095       8.863636              3.2      20.0   57.611255
1              14.0       5.181818             10.4      17.0   64.081818
2         13.714286       8.590909              6.4       6.0   53.276623
3         13.428571      10.636364             14.8      12.0    63.60303
4         13.333333      11.181818              8.8      12.0   62.219913
5          12.47619      10.227273              7.2       1.0   49.236797
6         12.190476       9.954545             12.4       0.0   50.259307
7         12.857143       9.818182              8.8       0.0   50.522944
8         11.714286       7.363636             18.0       2.0   55.744589
9          7.238095       9.409091              3.6       3.0   38.723377
10        14.380952      13.772727             16.8      19.0   80.025108
11        14.380952       7.772727             20.0       7.0   65.225108
12        10.952381       7.363636             10.0      11.0   50.149351
13         12.47619       7.227273              9.6       4.0    50.44632
14          9.52381       3.545455             15.6      14.0   55.169264
15        11.047619       8.318182             19.6       5.0   58.370563
16        13.238095       7.909091              0.8      11.0   48.542424
17         12.47619       9.136364             16.4       1.0   54.488745
18        13.714286       3.954545              9.6       5.0   46.197403
19         9.714286       3.818182              5.6       3.0   37.370563
20         9.714286       4.363636              6.0      14.0   45.149351
21        11.047619       8.181818              6.0      20.0   55.824675
22        13.904762       3.954545              8.8      18.0   60.968831
23         14.47619       9.681818              9.2      11.0   60.548485
24        11.619048       8.318182             11.2      15.0   61.137229
25        13.809524       7.636364              2.8      17.0   55.888745
26        10.095238            9.0              0.4       3.0   36.185714
27        11.904762       9.954545              6.8      17.0   58.397403
28        12.666667       8.045455             19.6       3.0   58.431169
29        12.571429       7.090909             11.2       4.0   52.719481
30        15.047619       9.818182              2.8      12.0   55.261039
31        14.095238           10.5             16.8      19.0   74.919048
32         8.380952       3.136364             16.0       3.0   47.541126
33        11.142857       7.636364              6.8      10.0   50.579221
34         10.47619       3.136364              8.0      10.0   46.136364
35        14.190476       8.590909              5.6       7.0   52.048052
36        11.904762       5.454545              0.4      17.0   50.711688
37        11.047619       7.909091              6.4      19.0   61.975758
38             12.0       6.136364              2.0       7.0   42.731602
39        11.619048       8.045455              1.2      14.0   49.745455
40        11.142857           10.5             12.8      20.0    71.82381
41         9.809524       8.727273             18.8       8.0   61.408225

   Grades
0       D
1       C
2       D
3       C
4       C
5       F
6       D
7       D
8       D
9       F
10     B+
11     C+
12      D
13      D
14      D
15      D
16      F
17      D
18      F
19      F
20      F
21      D
22      C
23      C
24      C
25      D
26      F
27      D
28      D
29      D
30      D
31      B
32      F
33      D
34      F
35      D
36      D
37      C
38      F
39      F
40      B
41      C
Enter 0 to Enter in other class and 5 to continue
Enter: 2
Enter 1 to display class Result
 Enter 2 to generate class result in .csv file
 Enter 3 to search the reslut of a student
Enter: 3
Enter the roll number of the student to search the result211214
   Roll numbers      Names Lab Performance Total Lab Report Total  \
16       211214  Samiullah             15.595238        13.238095

   Mid Term Total Final Term Total CEA Total Grand Total Grades
16       7.909091              0.8      11.0   48.542424      F
Enter 0 to Enter in other class and 5 to continue
Enter: 0
Press 1 for CE-112L MTS II B
Press 2 for CE-112L MTS II-A
Press 3 for CE-112L BEEP II-A
Press 4 for CE-115L BEBME 1A.
Enter: 3
Enter the Lab report weightage: 20
Enter the Lab Performance weightage: 10
Enter the Mid Term weightage: 20
Enter the Final Term weightage: 25
Enter the CEA weightage: 25
Enter 1 to display class Result
 Enter 2 to generate class result in .csv file
 Enter 3 to search the reslut of a student
Enter: 1
   Roll numbers                          Names Lab Performance Total  \
0        210319           Muhammad Ammar Bajwa              7.095238
1        210323                 Waleed Hussain              5.809524
2        210325                 Shahzaib Malik              6.904762
3        210327         Muhammad Tayyab Saddiq              6.047619
4        210331              Hadia Zainab Raza               3.47619
5        210335  Syeda Imtashal Fatima Jaffari              5.095238
6        210339                 Azlan Muhammad               4.47619
7        210341                 Abdullah Zahid              8.095238
8        210351                 Muammar Rehman              6.619048
9        210355                  Abdullah Khan              4.333333
10       210357                   Usama Khalid              7.809524
11       210359                 Muhammad Kazim              7.380952
12       210363                 Muhammad Talha              3.047619
13       210365                 Muhammad Usman              6.904762
14       210369                Mudassar Zahoor              5.238095
15       210371                   Abdul Baasit              5.857143
16       210373                    Taha Khalid              6.095238
17       210377              Abdullah Zulfiqar              6.190476
18       210379                 Usama Zulfiqar              6.761905
19       210381            Ahmad Mahtab Cheema              7.809524
20       210383                   Adnan Bashir              6.952381
21       211986               Shaoib ul Hassan              6.428571
22       211988              Muhammad Ali Khan              6.333333

   Lab Report Total Mid Term Total Final Term Total CEA Total Grand Total  \
0         12.095238      15.454545             19.5      8.75   62.895022
1         12.571429      12.363636              9.5     18.75   58.994589
2          15.52381      11.090909             19.0      25.0   77.519481
3         10.190476       8.181818             15.5      17.5   57.419913
4              12.0      10.727273              6.5      20.0   52.703463
5         11.238095      10.181818             12.5       2.5   41.515152
6          8.857143       8.363636             22.0      17.5    61.19697
7          14.47619      12.545455             12.0      3.75   50.866883
8         10.761905       9.636364             15.5       5.0   47.517316
9         11.333333       5.272727              7.0      22.5   50.439394
10        11.714286       8.727273             11.0      8.75   48.001082
11        12.571429           12.0             22.0      8.75   62.702381
12        11.142857       2.909091             23.5     23.75   64.349567
13        14.190476      10.181818              0.5     16.25   48.027056
14         15.52381      14.363636             17.0       0.0   52.125541
15        15.809524      10.909091              9.0     18.75   60.325758
16         10.47619      11.272727             17.0       5.0   49.844156
17        11.428571      10.363636             16.0      1.25   45.232684
18        12.571429      10.363636             12.0      3.75    45.44697
19        12.285714      12.545455             20.0       5.0   57.640693
20        10.285714       6.909091              3.0      22.5   49.647186
21        11.809524      11.272727             12.0      20.0   61.510823
22         11.52381       4.727273             24.5     23.75   70.834416

   Grades
0       C
1       D
2      B+
3       D
4       D
5       F
6       C
7       D
8       F
9       D
10      F
11      C
12      C
13      F
14      D
15      C
16      F
17      F
18      F
19      D
20      F
21      C
22      B
Enter 0 to Enter in other class and 5 to continue
Enter: 2
Enter 1 to display class Result
 Enter 2 to generate class result in .csv file
 Enter 3 to search the reslut of a student
Enter: 3
Enter the roll number of the student to search the result210359
   Roll numbers           Names Lab Performance Total Lab Report Total  \
11       210359  Muhammad Kazim              7.380952        12.571429

   Mid Term Total Final Term Total CEA Total Grand Total Grades
11           12.0             22.0      8.75   62.702381      C
Enter 0 to Enter in other class and 5 to continue
Enter: 0
Press 1 for CE-112L MTS II B
Press 2 for CE-112L MTS II-A
Press 3 for CE-112L BEEP II-A
Press 4 for CE-115L BEBME 1A.
Enter: 4
Enter the Lab report weightage: 20
Enter the Lab Performance weightage: 20
Enter the Mid Term weightage: 20
Enter the Final Term weightage: 20
Enter the CEA weightage: 20
Enter 1 to display class Result
 Enter 2 to generate class result in .csv file
 Enter 3 to search the reslut of a student
Enter: 1
   Roll numbers                       Names Lab Performance Total  \
0        211135                  Muniba Ali             17.047619
1        211136                Ifrah Kamran             15.714286
2        211142             Iman Ali Shahid             12.666667
3        211143              Kahab Abdullah             11.714286
4        211145                 Noor-Ul-Ain             15.142857
5        211148           Syeda Iqra Naveen             13.047619
6        211149               Aamnah Sultan             13.619048
7        211150              Muhammad Ahmed             11.714286
8        211152    Muhammad Arslan Siddique             13.047619
9        211153            Muqaddas Shakeel             12.666667
10       211154                 Anum Faisal             10.666667

In [34]:
LabReport=int(input("Enter the Lab report weightage: "))
LabPerformance=int(input("Enter the Lab Performance weightage: "))
MidTerm=int(input("Enter the Mid Term weightage: "))
FinalTerm=int(input("Enter the Final Term weightage: "))
CEA=int(input("Enter the CEA weightage: "))
weightages={
        "LR":LabReport,
        "LP":LabPerformance,
        "MT":MidTerm,
        "FT":FinalTerm,
        "CEA":CEA
        }
Result(weightages,MTS2A)

Enter the Lab report weightage: 20
Enter the Lab Performance weightage: 20
Enter the Mid Term weightage: 20
Enter the Final Term weightage: 20
Enter the CEA weightage: 20

,Roll numbers,Names,Lab Performance Total,Lab Report Total,Mid Term Total,Final Term Total,CEA Total,Grand Total,Grades
0,201113,Shaheer Faisal,13.047619,9.238095,11.818182,3.2,20.0,57.303896,D
1,201128,Mati Ur Rehman Ahmed,14.0,14.0,6.909091,10.4,17.0,62.309091,C
2,210559,Taimoor Qamar,14.857143,13.714286,11.454545,6.4,6.0,52.425974,D
3,211176,Muhammad Junaid,10.190476,13.428571,14.181818,14.8,12.0,64.600866,C
4,211184,Hafiz Haider Farooq,13.52381,13.333333,14.909091,8.8,12.0,62.566234,C
5,211187,Muhammad Taha Khalid,14.666667,12.47619,13.636364,7.2,1.0,48.979221,F
6,211190,Areeba Nazim,12.571429,12.190476,13.272727,12.4,0.0,50.434632,D
7,211191,Muhammad Mubeen Anjum,15.238095,12.857143,13.090909,8.8,0.0,49.986147,F
8,211194,Sania Ali,13.333333,11.714286,9.818182,18.0,2.0,54.865801,D
9,211196,Norose Chohan,12.380952,7.238095,12.545455,3.6,3.0,38.764502,F
10,211197,Shazil Sajjad,12.857143,14.380952,18.363636,16.8,19.0,81.401732,B+
11,211199,Abdullah Bin Masood,12.857143,14.380952,10.363636,20.0,7.0,64.601732,C
12,211200,Madeeha Fayyaz,8.666667,10.952381,9.818182,10.0,11.0,50.437229,D
13,211202,Shereen Zainab,13.714286,12.47619,9.636364,9.6,4.0,49.42684,F
14,211209,Arooj Aftab,10.0,9.52381,4.727273,15.6,14.0,53.851082,D
15,211212,Abdullah Ilyas,11.52381,11.047619,11.090909,19.6,5.0,58.262338,D
16,211214,Samiullah,12.47619,13.238095,10.545455,0.8,11.0,48.05974,F
17,211215,Waris Shah,12.380952,12.47619,12.181818,16.4,1.0,54.438961,D
18,211217,Rafay Ali Hassnain,11.142857,13.714286,5.272727,9.6,5.0,44.72987,F
19,211221,Areeba Nisar,12.190476,9.714286,5.090909,5.6,3.0,35.595671,F
20,211223,Hassan Ali Janjua,8.857143,9.714286,5.818182,6.0,14.0,44.38961,F
21,211224,Muhammad Shehroz Khan,8.47619,11.047619,10.909091,6.0,20.0,56.4329,D
22,211230,Hasnain Khan Afridi,13.047619,13.904762,5.272727,8.8,18.0,59.025108,D
23,211232,Muhammad Waqar,12.952381,14.47619,12.909091,9.2,11.0,60.537662,C
24,211233,Muhammad Abdullah,12.0,11.619048,11.090909,11.2,15.0,60.909957,C
25,211236,Muhammad Muzammil,11.714286,13.809524,10.181818,2.8,17.0,55.505628,D
26,211239,Danyal Ahmed,10.952381,10.095238,12.0,0.4,3.0,36.447619,F
27,211242,Ali Torab,10.190476,11.904762,13.272727,6.8,17.0,59.167965,D
28,211254,Rabiah,12.095238,12.666667,10.727273,19.6,3.0,58.089177,D
29,211257,Etizaz Zahid,14.285714,12.571429,9.454545,11.2,4.0,51.511688,D
30,211260,Salahuddin Muhammad Abdullah,12.47619,15.047619,13.090909,2.8,12.0,55.414719,D
31,211263,Muhammad Mubeen Rubbani,11.619048,14.095238,14.0,16.8,19.0,75.514286,B+
32,211266,Alishba Syed,13.619048,8.380952,4.181818,16.0,3.0,45.181818,F
33,211269,Salman Ali,12.0,11.142857,10.181818,6.8,10.0,50.124675,D
34,211275,Saif Ur Rehman,11.619048,10.47619,4.181818,8.0,10.0,44.277056,F
35,211278,Ali Hassan,13.333333,14.190476,11.454545,5.6,7.0,51.578355,D
36,211281,Muhammad Ahsan Mujahid,12.761905,11.904762,7.272727,0.4,17.0,49.339394,F
37,211284,Izza Nadeem,14.095238,11.047619,10.545455,6.4,19.0,61.088312,C
38,211287,Hassan Hafeez,12.47619,12.0,8.181818,2.0,7.0,41.658009,F
39,212002,Muhammad Sohaib,11.904762,11.619048,10.727273,1.2,14.0,49.451082,F
40,212003,Faizan Ahmed Siddiqui,13.904762,11.142857,14.0,12.8,20.0,71.847619,B
41,212004,Azhar Ali,12.857143,9.809524,11.636364,18.8,8.0,61.10303,C